### PR TITLE
Update opentracing to 0.33.0

### PR DESCRIPTION
**Pull request by eugeniyk**
Opentracing 0.33.0 is current standard which is not compatible with 0.31
Main changes were separation of span lifetime vs scope lifetime.

In CB every span is generated with connection to parent span, which doesn't require any scope management:

```java
Span span = env.tracer().buildSpan("...").asChildOf(parent). ... .start`
```

Reopened from #22 with single github username

### CODE REVIEW

**Comment by eugeniyk** [comment]
@daschl pls review once again

**Comment by daschl** [comment]
@eugeniyk what do you think about my sdk 3 proposal in the other PR ?

**Comment by eugeniyk** [comment]
@daschl just saw it, thanks
Yes, that's my next move once we'll migrate to couchbase 6.+, there we'll just use 3.x driver
This PR mostly related to 4.x - 5.x versions which we are now

**Comment by eugeniyk** [comment]
Closing PR as 2.7.x no longer in active development
Long live the 3.x!

**Pull request closed without merging**
