### PR TITLE
add test2.txt to gitignore (dummy PR2)

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Transferred to Couchbase Review site at http://review.couchbase.org/#/c/55492.

::SDKBOT/PR:created

**Comment by brett19** [comment]
Updated commits pushed to Couchbase Review site at http://review.couchbase.org/#/c/55492.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
Updated commits pushed to Couchbase Review site at http://review.couchbase.org/#/c/55492.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
This changeset was completed in Gerrit.  Closing pull request.

::SDKBOT/PR:closed

**Comment by brett19** [comment]
This changeset was completed in Gerrit.  Closing pull request.

::SDKBOT/PR:closed

**Comment by brett19** [comment]
Unfortunately we cannot confirm that you have signed our CLA and must close this Pull Request.  We sincerely appreciate your submission and hope that you will register and resubmit this Pull Request in the future!

::SDKBOT/PR:timeout

**Comment by brett19** [comment]
Unfortunately we cannot confirm that you have signed our CLA and must close this Pull Request.  We sincerely appreciate your submission and hope that you will register and resubmit this Pull Request in the future!

::SDKBOT/PR:timeout

**Comment by brett19** [comment]
This changeset was completed in Gerrit.  Closing pull request.

::SDKBOT/PR:closed

**Comment by brett19** [comment]
::SDKBOT/PR:test

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
This changeset was completed in Gerrit.  Closing pull request.

::SDKBOT/PR:closed

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
.

**Comment by brett19** [comment]
::SDKBOT/PR:reset

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
::SDKBOT/PR:reset

**Comment by mnunberg** [comment]
testing testing 123

**Comment by mnunberg** [comment]
....

**Comment by brett19** [comment]
asd

**Comment by mnunberg** [comment]
another time

**Comment by mnunberg** [comment]
,,..

**Comment by mnunberg** [comment]
....

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Updated commit (68600646deba29443b53e392f9ff59f1694c958b) pushed to Couchbase Review site.

::SDKBOT/PR:pushed

**Comment by brett19** [comment]
This changeset was completed in Gerrit.  Closing pull request.

::SDKBOT/PR:closed

**Pull request closed without merging**
