### PR TITLE
Update opentracing 0.33

### PR DESCRIPTION
**Pull request by eugeniyk**
Opentracing 0.33 is current standard which is not compatible with 0.31
Main changes were separation of span lifetime vs scope lifetime.

In CB every span is generated with connection to parent span, which doesn't require any scope management:
```
Span span = env.tracer().buildSpan("...").asChildOf(parent). ... .start`
```

I wasn't able to run integration tests - any tutorial which dependency to use? maybe you should add docker compose or smth?

### CODE REVIEW

**Comment by eugeniyk** [comment]
@daschl could you please take a look? I want to know whether to wait for upstream or keep going with 0.31 compatibility mode.

**Comment by daschl** [comment]
@eugeniyk thanks for the heads up - this is a tricky one .. ideally we'd need to do another minor release for this, since technically it breaks current code if they rely on the older version. For SDK 3 we are planning to track the latest opentracing and opentelemetry versions. 

I'll discuss with the team and get back to you.

**Comment by eugeniyk** [comment]
Btw another option - we can bump the version to 0.32 keeping the changes - it has compatibility layer between `0.31` and `0.33` so clients who are using 0.31 won't suffer

**Comment by daschl** [comment]
@eugeniyk thanks for the additional info, I guess I need to do a little more research on changes and impact - will keep you posted!

**Comment by daschl** [comment]
@eugeniyk sorry this has stalled a bit, but I haven't forgotten about it - will keep you updated!

**Comment by eugeniyk** [comment]
@daschl how can I have agreement for github account that is under github enterprise?
I can reopen this PR under squashed commit github.com acc as well

**Comment by daschl** [comment]
@eugeniyk we would have to get the change into gerrit anyways and there you can submit it with the one you signed the CLA.

I want to propose another path as well: have you considered moving to SDK 3 already? Because SDK 3 ships a tracing-opentracing module based on 0.33 and I'd hope it just "works" for you. (https://search.maven.org/search?q=a:tracing-opentracing)

For usage see: https://github.com/couchbase/couchbase-jvm-clients/blob/master/tracing-opentracing/src/integrationTest/java/com/couchbase/client/tracing/opentracing/OpenTracingIntegrationTest.java#L52

Note that this is technically volatile API though, but since the API surface is not that big it won't change a lot in the future I think.

**Comment by eugeniyk** [comment]
Closing this and continue in #23

**Pull request closed without merging**
