### PR TITLE
Fix wrong class name in toString

### PR DESCRIPTION
**Pull request by micopiira**

### CODE REVIEW

**Comment by subalakr** [comment]
Hi @micopiira,

Thanks for PR. If you can sign the CLA for Gerrit, we can take and merge it there.
The easiest way to do it is to follow the link below, sign in with your GitHub account and then follow through the steps provided on that page to sign an 'Individual' agreement: http://review.couchbase.org/#/settings/new-agreement.

**Comment by micopiira** [comment]
> Hi @micopiira,
> 
> Thanks for PR. If you can sign the CLA for Gerrit, we can take and merge it there.
> The easiest way to do it is to follow the link below, sign in with your GitHub account and then follow through the steps provided on that page to sign an 'Individual' agreement: http://review.couchbase.org/#/settings/new-agreement.

Signed.

**Comment by subalakr** [comment]
Merged and released with 1.7.2.

**Comment by ingenthr** [comment]
Done over on review.couchbase.org.

**Pull request closed without merging**
